name: Sync Data

on:
  schedule:
    # Gira alle 10:30 UTC (12:30 italiane) e alle 16:30 UTC (18:30 italiane)
    - cron: '30 10,16 * * *'
  workflow_dispatch: # Permette di lanciarlo a mano per test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python cgsse.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git add .
          # Evita errore se non ci sono nuovi dati
          git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornamento dati scioperi" && git push)
